version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/application.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: coder

build:
  run_buildscript: false
  toolchains: []

images:
  - id: coder
    target: service
    service: coder-service
    source: ghcr.io/coder/coder
    channel: stable
    sort: semver
    tag_regex: '^v?2\.\d+\.\d+$'
    delivery:
      mode: lazycat

stores:
  official:
    enabled: true
    skip_if_version_exists: true
    create_if_missing: true
    changelog_locales: [zh, en]
    retry:
      enabled: false
      max_attempts: 3
      initial_delay: 2s
      max_delay: 30s
    application:
      language: zh
      name: Coder
      source: https://github.com/lazycat-contrib/coder-lzcapp
      source_author: lazycat-contrib
  private:
    enabled: true
    skip_if_version_exists: true
    name: Coder
    summary: Coder for LazyCat
