name: Coder
package: community.lazycat.app.coder
version: 2.28.6
min_os_version: 1.3.8
description: "Self-Hosted Cloud Development Environments"
license: AGPL-3.0
homepage: https://github.com/coder/coder
author: Coder

application:
  subdomain: coder
  oidc_redirect_path: /api/v2/users/oidc/callback
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://coder-service:7080/

services:
  database:
    image: registry.lazycat.cloud/czyt/library/postgres:dcad62678269633a
    environment:
      - POSTGRES_USER=coder
      - POSTGRES_PASSWORD=coderpassword
      - POSTGRES_DB=coderdb
    binds:
      - /lzcapp/var/db:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U coder -d coderdb
      interval: 5s
      timeout: 5s
      retries: 5
    cpu_shares: 512
    mem_limit: 1024M

  coder-service:
    # ghcr.io/coder/coder:v2.28.6
    image: registry.lazycat.cloud/czyt/coder/coder:9d2f5ca4beeaa082
    user: "1000"
    environment:
      # 数据库配置
      - CODER_PG_CONNECTION_URL=postgresql://coder:coderpassword@database/coderdb?sslmode=disable
      - CODER_HTTP_ADDRESS=0.0.0.0:7080
      # 访问地址配置
{{if .U.enable_custom_access_domain}}
      - CODER_ACCESS_URL=https://{{.U.custom_access_domain}}
{{else}}
      - CODER_ACCESS_URL=https://${LAZYCAT_APP_DOMAIN}
{{end}}

      # OIDC 认证配置 - 由懒猫统一 OIDC 系统自动注入
      - CODER_OIDC_ISSUER_URL=${LAZYCAT_AUTH_OIDC_ISSUER_URI}
      - CODER_OIDC_CLIENT_ID=${LAZYCAT_AUTH_OIDC_CLIENT_ID}
      - CODER_OIDC_CLIENT_SECRET=${LAZYCAT_AUTH_OIDC_CLIENT_SECRET}
      - CODER_OIDC_EMAIL_DOMAIN=
      - CODER_OIDC_SCOPES=openid,profile,email
      - CODER_OIDC_SIGN_IN_TEXT=Sign in with Lazycat
      - CODER_OIDC_ICON_URL=
      - CODER_OIDC_IGNORE_EMAIL_VERIFIED=false
      - CODER_OIDC_IGNORE_USERINFO=false
      - CODER_DISABLE_PASSWORD_AUTH={{ .U.disable_password_auth }}

    binds:
      - /lzcapp/var/data:/home/coder
    setup_script: |
        chown -R 1000:1000 /home/coder

    depends_on:
      - database
    cpu_shares: 1024
    mem_limit: 2048M

locales:
  en:
    name: "Coder"
    description: "Self-Hosted Cloud Development Environments"
  zh:
    name: "Coder"
    description: "自托管云端开发环境，在任何设备上使用浏览器访问完整的开发环境"
