package: community.lazycat.app.coder
version: 2.36.0
name: Coder
description: Self-Hosted Cloud Development Environments
min_os_version: 1.3.8
license: AGPL-3.0
homepage: https://github.com/coder/coder
author: Coder
locales:
  en:
    name: Coder
    description: Self-Hosted Cloud Development Environments
  zh:
    name: Coder
    description: 自托管云端开发环境，在任何设备上使用浏览器访问完整的开发环境
